import { Complaint, StaffUser, Assessment, Response, ComplaintStatus } from './types';

export const STATUSES: ComplaintStatus[] = [
  'New', 'Categorized', 'Assigned', 'In Progress',
  'Sent to Directorate', 'Assessment Completed', 'Responded', 'Closed', 'Rejected'
];

export const STATUS_FLOW: ComplaintStatus[] = [
  'New', 'Categorized', 'Assigned', 'In Progress',
  'Sent to Directorate', 'Assessment Completed', 'Responded', 'Closed'
];

export const CATEGORIES = [
  { name: 'Tax Assessment', subcategories: ['Income Tax', 'VAT', 'Corporate Tax', 'Withholding Tax'] },
  { name: 'Service Delivery', subcategories: ['Delay', 'Quality', 'Accessibility', 'Staff Behavior'] },
  { name: 'Refund', subcategories: ['Pending Refund', 'Incorrect Amount', 'Delayed Processing'] },
  { name: 'Registration', subcategories: ['TIN Issue', 'Business Registration', 'Update Request'] },
];

export const DIRECTORATES = [
  'Domestic Tax', 'Customs & Excise', 'Legal Affairs', 'Taxpayer Services', 'Audit & Investigation'
];

export const TAX_CENTERS = [
  'Addis Ababa North', 'Addis Ababa South', 'Addis Ababa East', 'Oromia Region', 'Amhara Region', 'SNNPR', 'Tigray Region'
];

export const mockStaffUsers: StaffUser[] = [
  { id: '1', name: 'Admin User', email: 'admin@portal.gov', role: 'admin' },
  { id: '2', name: 'Director General', email: 'director@portal.gov', role: 'director' },
  { id: '3', name: 'Team Lead A', email: 'teamlead@portal.gov', role: 'team_leader' },
  { id: '4', name: 'Officer Ahmed', email: 'ahmed@portal.gov', role: 'officer', directorate: 'Domestic Tax' },
  { id: '5', name: 'Officer Sara', email: 'sara@portal.gov', role: 'officer', directorate: 'Customs & Excise' },
  { id: '6', name: 'Dir. Domestic Tax', email: 'domestic@portal.gov', role: 'directorate', directorate: 'Domestic Tax' },
];

export const mockComplaints: Complaint[] = [
  {
    id: 'CMP-2026-001',
    complaint_code: 'CMP-2026-001',
    case_status: 'In Progress',
    taxpayer_name: 'John Doe Business PLC',
    tin: '1234567890',
    taxpayer_phone: '+251911223344',
    complainant_name: 'John Doe',
    complainant_phone: '+251911223344',
    complainant_email: 'johndoe@email.com',
    category_id: 'CAT-001',
    sub_category_id: 'SUB-001',
    complaints_on: 'Domestic Tax Directorate',
    status_id: 'STS-004',
    status: 'In Progress',
    case_type: 'Business',
    applied_date: '2026-01-15',
    complaint_title: 'Incorrect Annual Income Tax Assessment',
    details: 'Incorrect tax assessment on my annual income tax filing for 2025.',
    machine_code: 'MCH-001',
    reference_number: 'REF-2026-001',
    tax_center: 'Addis Ababa North',
    assigned_to: '4',
    // legacy compat
    fullName: 'John Doe',
    contact: '+251911223344',
    category: 'Tax Assessment',
    subcategory: 'Income Tax',
    assignedOfficer: '4',
    directorate: 'Domestic Tax',
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-02-01T14:20:00Z',
  },
  {
    id: 'CMP-2026-002',
    complaint_code: 'CMP-2026-002',
    case_status: 'Sent to Directorate',
    taxpayer_name: 'Jane Smith Trading',
    tin: '0987654321',
    taxpayer_phone: '+251922334455',
    complainant_name: 'Jane Smith',
    complainant_phone: '+251922334455',
    complainant_email: 'janesmith@email.com',
    category_id: 'CAT-003',
    sub_category_id: 'SUB-007',
    complaints_on: 'Customs & Excise Directorate',
    status_id: 'STS-005',
    status: 'Sent to Directorate',
    case_type: 'Business',
    applied_date: '2026-01-20',
    complaint_title: 'Delayed VAT Refund Q3 2025',
    details: 'Delayed VAT refund for Q3 2025, submitted documents 3 months ago.',
    machine_code: 'MCH-002',
    reference_number: 'REF-2026-002',
    tax_center: 'Addis Ababa South',
    assigned_to: '5',
    fullName: 'Jane Smith',
    contact: '+251922334455',
    category: 'Refund',
    subcategory: 'Delayed Processing',
    assignedOfficer: '5',
    directorate: 'Customs & Excise',
    createdAt: '2026-01-20T11:00:00Z',
    updatedAt: '2026-02-05T16:45:00Z',
  },
  {
    id: 'CMP-2026-003',
    complaint_code: 'CMP-2026-003',
    case_status: 'New',
    taxpayer_name: 'Ali Hassan',
    tin: '1122334455',
    taxpayer_phone: '+251933445566',
    complainant_name: 'Ali Hassan',
    complainant_phone: '+251933445566',
    complainant_email: 'alihassan@email.com',
    category_id: 'CAT-004',
    sub_category_id: 'SUB-010',
    complaints_on: 'Taxpayer Services',
    status_id: 'STS-001',
    status: 'New',
    case_type: 'Individual',
    applied_date: '2026-02-10',
    complaint_title: 'Unable to Update Business Registration',
    details: 'Unable to update my business registration details online.',
    tax_center: 'Oromia Region',
    fullName: 'Ali Hassan',
    contact: '+251933445566',
    category: 'Registration',
    subcategory: 'Update Request',
    createdAt: '2026-02-10T08:15:00Z',
    updatedAt: '2026-02-10T08:15:00Z',
  },
  {
    id: 'CMP-2026-004',
    complaint_code: 'CMP-2026-004',
    case_status: 'Assigned',
    taxpayer_name: 'Fatima Yusuf Enterprises',
    tin: '5566778899',
    taxpayer_phone: '+251944556677',
    complainant_name: 'Fatima Yusuf',
    complainant_phone: '+251944556677',
    complainant_email: 'fatima.yusuf@email.com',
    category_id: 'CAT-002',
    sub_category_id: 'SUB-006',
    complaints_on: 'Taxpayer Services Branch Office',
    status_id: 'STS-003',
    status: 'Assigned',
    case_type: 'Business',
    applied_date: '2026-02-08',
    complaint_title: 'Unhelpful Staff at Branch Office',
    details: 'Staff at the branch office were unhelpful during my visit.',
    machine_code: 'MCH-004',
    reference_number: 'REF-2026-004',
    tax_center: 'Amhara Region',
    assigned_to: '4',
    fullName: 'Fatima Yusuf',
    contact: '+251944556677',
    category: 'Service Delivery',
    subcategory: 'Staff Behavior',
    assignedOfficer: '4',
    directorate: 'Taxpayer Services',
    createdAt: '2026-02-08T13:00:00Z',
    updatedAt: '2026-02-09T10:30:00Z',
  },
  {
    id: 'CMP-2026-005',
    complaint_code: 'CMP-2026-005',
    case_status: 'Responded',
    taxpayer_name: 'Michael Tesfaye Co.',
    tin: '6677889900',
    taxpayer_phone: '+251955667788',
    complainant_name: 'Michael Tesfaye',
    complainant_phone: '+251955667788',
    complainant_email: 'michael.tesfaye@email.com',
    category_id: 'CAT-001',
    sub_category_id: 'SUB-004',
    complaints_on: 'Domestic Tax Directorate',
    status_id: 'STS-007',
    status: 'Responded',
    case_type: 'Individual',
    applied_date: '2026-01-25',
    complaint_title: 'Incorrect Withholding Tax on Payslip',
    details: 'Withholding tax amount is incorrectly calculated on my payslip.',
    machine_code: 'MCH-005',
    reference_number: 'REF-2026-005',
    tax_center: 'Addis Ababa East',
    assigned_to: '5',
    fullName: 'Michael Tesfaye',
    contact: '+251955667788',
    category: 'Tax Assessment',
    subcategory: 'Withholding Tax',
    assignedOfficer: '5',
    directorate: 'Domestic Tax',
    createdAt: '2026-01-25T07:45:00Z',
    updatedAt: '2026-02-11T09:00:00Z',
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: 'ASS-001',
    complaint_id: 'CMP-2026-001',
    assessment_status: 'Sent',
    assess_no: 'ASN-2026-001',
    explanation_topic: 'Income Tax Discrepancy',
    sent_to: 'John Doe Business PLC',
    sent_date: '2026-01-28',
    explanation_date: '2026-02-05',
    sent_by: 'Officer Ahmed',
    // legacy
    complaintId: 'CMP-2026-001', assessedBy: '4', type: 'officer',
    content: 'Reviewed tax filing. Found discrepancy in reported income vs employer records.',
    createdAt: '2026-01-28T10:00:00Z',
  },
  {
    id: 'ASS-002',
    complaint_id: 'CMP-2026-002',
    assessment_status: 'Responded',
    assess_no: 'ASN-2026-002',
    explanation_topic: 'VAT Refund Verification',
    sent_to: 'Jane Smith Trading',
    sent_date: '2026-02-03',
    explanation_date: '2026-02-10',
    sent_by: 'Officer Sara',
    // legacy
    complaintId: 'CMP-2026-002', assessedBy: '5', type: 'officer',
    content: 'All refund documents verified. Amount eligible for refund confirmed.',
    createdAt: '2026-02-03T11:30:00Z',
  },
  {
    id: 'ASS-003',
    complaint_id: 'CMP-2026-005',
    assessment_status: 'Closed',
    assess_no: 'ASN-2026-003',
    explanation_topic: 'Withholding Tax Correction',
    sent_to: 'Domestic Tax Directorate',
    sent_date: '2026-02-08',
    explanation_date: '2026-02-12',
    sent_by: 'Dir. Domestic Tax',
    // legacy
    complaintId: 'CMP-2026-005', assessedBy: '6', type: 'directorate',
    content: 'Confirmed withholding tax calculation error. Correction issued.',
    createdAt: '2026-02-08T14:00:00Z',
  },
  {
    id: 'ASS-004',
    complaint_id: 'CMP-2026-004',
    assessment_status: 'Pending',
    assess_no: 'ASN-2026-004',
    explanation_topic: 'Staff Conduct Review',
    sent_to: 'Taxpayer Services',
    sent_date: '2026-02-09',
    sent_by: 'Team Lead A',
    // legacy
    complaintId: 'CMP-2026-004', assessedBy: '3', type: 'officer',
    content: 'Staff behavior complaint under review.',
    createdAt: '2026-02-09T10:30:00Z',
  },
];

export const mockResponses: Response[] = [
  {
    id: 'RES-001',
    complaintId: 'CMP-2026-005',
    respondedBy: '5',
    content: 'Dear Mr. Tesfaye, the withholding tax error has been corrected. Your updated tax certificate is available for collection at the Addis Ababa East Tax Center.',
    sentToUser: true,
    createdAt: '2026-02-11T09:00:00Z',
    response_status: 'Sent',
    subject: 'Resolution: Incorrect Withholding Tax on Payslip',
    recipient_name: 'Michael Tesfaye',
    recipient_email: 'michael.tesfaye@email.com',
    sent_date: '2026-02-11',
    approved_by: 'Team Lead A',
    approved_date: '2026-02-10',
    notes: 'Correction applied and certificate issued.',
  },
  {
    id: 'RES-002',
    complaintId: 'CMP-2026-002',
    respondedBy: '5',
    content: 'Dear Ms. Smith, we have reviewed your VAT refund request. All submitted documents have been verified and your refund of ETB 85,000 has been approved.',
    sentToUser: false,
    createdAt: '2026-02-13T11:00:00Z',
    response_status: 'Pending Approval',
    subject: 'VAT Refund Request — Decision',
    recipient_name: 'Jane Smith',
    recipient_email: 'janesmith@email.com',
    notes: 'Awaiting Team Lead signature before dispatch.',
  },
  {
    id: 'RES-003',
    complaintId: 'CMP-2026-004',
    respondedBy: '4',
    content: 'Dear Ms. Yusuf, we sincerely apologize for the inconvenience experienced at our branch office. Corrective measures have been taken with the staff concerned.',
    sentToUser: false,
    createdAt: '2026-02-14T08:30:00Z',
    response_status: 'Draft',
    subject: 'Staff Conduct Complaint — Follow-up',
    recipient_name: 'Fatima Yusuf',
    recipient_email: 'fatima.yusuf@email.com',
    notes: 'Draft pending review.',
  },
];
